### ISSUE TITLE
Apparent typo in Step Functions definition

### ISSUE THREAD

**Issue by mmonette** [aws-samples/aws-stepfunctions-examples#16]
There appears to be a typo in sam/app-control-concurrency-with-dynamodb/statemachines/dynamodb-semaphore-cleanfromincomplete.asl.json that may cause a problem in cleanup.  There are 3 instances of "lockowerid" instead of "lockownerid".

**Comment by JustinCallison** [comment]
Thanks @mmonette, I updated that. This wasn't a functional problem because that's just the internal label used within the DDB statements. It looks strange nonetheless, so I fixed it.
